[package]
name = "aether_of_enclaves"
version = "0.1.0"
authors = ["samuel"]

[dependencies]
piston = "0.35.0"
piston2d-graphics = "0.25.0"
pistoncore-glutin_window = "0.44.0"
piston2d-opengl_graphics = "0.51.0"
